### PR TITLE
Move to a pure golang implementation of crypt()

### LINKED ISSUE #49: Can't build on alpine linux
The used go-crypt module contains glibc specific code. Alpine linux is using musl instead of glibc.

```
owncloud/idm # make
running gofmt ...
retrieving dependencies ...
# github.com/Azure/go-ntlmssp v0.0.0-20211209120228-48547f28849e
...
building cmd/idmd ...
CGO_ENABLED=1 go build \
        -mod=vendor \
        -trimpath \
        -tags release \
        -buildmode=exe \
        -ldflags '-s -w -buildid=reproducible/0.3.0-41-gb89b052 -X github.com/libregraph/idm/version.Version=0.3.0-41-gb89b052 -X github.com/libregraph/idm/version.BuildDate=2022-02-17T17:28:53Z -extldflags -static' \
        -o bin/idmd ./cmd/idmd
# github.com/amoghe/go-crypt
vendor/github.com/amoghe/go-crypt/version.go:6:10: fatal error: gnu/libc-version.h: No such file or directory
    6 | #include <gnu/libc-version.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:47: cmd/idmd] Error 2
```

### PR DESCRIPTION
**Pull request by rhafer**
Apart from build issues on non-Linux platforms (which might be ok). The
previously used go-crypt module does not build when using the musl libc
library as e.g. used in alpine linux. Using a pure go implementation
make things a lot easier.

Fixes #49

This will also get us rid of the nasty linker warnings when creating the static binary:

```
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/go-link-41928801/000004.o: in function `_cgo_3c1cec0c9a4e_C2func_getaddrinfo':
/tmp/go-build/cgo-gcc-prolog:58: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

Note: GehirnInc/crypt does currently not support the original DES crypt mechanism, but I really think we should not support that anyway. It's insecure.

### CODE REVIEW

**Review by longsleep — CHANGES_REQUESTED** [review]
This is not something I would.like to see. The library added here is old and probably does not support any modern crypt algs like glibc on Debian/Ubuntu does. Feel free to link details on details what algs are actually supported. I share more details when I have the time. But I strongly believe this is a bad idea.

**Comment by rhafer** [comment]
> This is not something I would.like to see.

Fair enough. Let's work this out.

>  The library added here is old 

Actually it's not much different to go-crypt in that regard ;-).

> and probably does not support any modern crypt algs like glibc on Debian/Ubuntu does.

Is there any specific algorithm you need to support? I guess your not referring to the stuff that is glibc (AFAIK the list of supported algorithms hasn't change there in years). Are you referring to besser82/libxcrypt? Some distros (not sure about debian) switched to that instead of the default libcrypt provided by glibc.

> Feel free to link details on details what algs are actually supported.

It supports md5 ($1$), apr ($apr1$), SHA256 ($5$) and SHA512 ($6$). Many of the newer algorithms from libxcrypt are missing indeed.

> I share more details when I have the time. But I strongly believe this is a bad idea.

We'd also be fine if we could make the ´{CRYPT}´ support optional. We don't really need that for our usecase. But we need to be able to build on alpine and with go-crypt (which also hasn't seen much love lately) that really sucks.

**Comment by rhafer** [comment]
Closing in favour of #51

**Comment by longsleep** [comment]
> Ok, I've submitted a couple of fixes to go-crypt so that it can also build on musl based systems (musl supports at least bcrypt and the shaXXX hashes formats). Let's see where this goes. Meanwhile I'll also create a new PR to allow to disable the `{CRYPT}` support in idm so that I am able to move forward with integrating idm into oCIS.

:+1: this is great - seems like the go-crypt stuff was merged and we can eventually update to that too to deal with tthis better.

**Comment by rhafer** [comment]
> seems like the go-crypt stuff was merged and we can eventually update to that too to deal with this better.

Yeah. I already bumped the go-crypt release. But I'd like to keep the `disable_crypt` for now as I just found I need another fix in  
go-crypt to cover another corner-case ...

**Pull request closed without merging**
